// Mock data for the app

export const categories = [
  { id: 1, name: "Diabetes Panel", icon: "🩸", color: "bg-blue-100" },
  { id: 2, name: "Thyroid Profile", icon: "🦋", color: "bg-purple-100" },
  { id: 3, name: "Liver Function", icon: "🫀", color: "bg-red-100" },
  { id: 4, name: "Kidney Function", icon: "💧", color: "bg-orange-100" },
  { id: 5, name: "Vitamin Profile", icon: "💊", color: "bg-yellow-100" },
  { id: 6, name: "Heart Health", icon: "❤️", color: "bg-pink-100" },
]

export const tests = [
  {
    id: 1,
    name: "HbA1c Test",
    category: "Diabetes Panel",
    categoryId: 1,
    price: 499,
    mrp: 699,
    discount: 29,
    description:
      "Measures average blood sugar levels over 3 months. This test is essential for diagnosing and monitoring diabetes.",
    preparationTime: "8-10 hours fasting",
    tat_time: "24 hours",
    sampleType: "Blood",
    fasting: "Required",
    ageGroup: "All ages",
    gender: "Both",
    parameters: 1,
    topSelling: false,
    recentBookings: 2450,
    alsoKnownAs: ["Glycated Hemoglobin", "A1C Test", "Hemoglobin A1c"],
    testCriteria: {
      eligible: "Anyone above 5 years of age can take this test",
      when: "If you have symptoms of diabetes or for regular monitoring",
      frequency: "Every 3-6 months for diabetic patients",
    },
    instructions: [
      "Fast for 8-10 hours before the test",
      "You can drink water during fasting",
      "Inform about any medications you're taking",
      "Avoid heavy exercise before the test",
    ],
    parameterDetails: [
      {
        name: "Glycated Hemoglobin (HbA1c)",
        description: "Measures the percentage of hemoglobin that has glucose attached to it",
        normalRange: "Below 5.7%",
      },
    ],
  },
  {
    id: 2,
    name: "Fasting Blood Sugar",
    category: "Diabetes Panel",
    categoryId: 1,
    price: 299,
    mrp: 450,
    discount: 34,
    description: "Measures blood glucose after fasting. Essential for diabetes screening and monitoring.",
    preparationTime: "8-10 hours fasting",
    tat_time: "6 hours",
    sampleType: "Blood",
    fasting: "Required",
    ageGroup: "All ages",
    gender: "Both",
    parameters: 1,
    topSelling: true,
    recentBookings: 5230,
    alsoKnownAs: ["FBS", "Fasting Glucose", "Fasting Blood Glucose"],
    testCriteria: {
      eligible: "Anyone above 5 years of age",
      when: "For diabetes screening or monitoring",
      frequency: "As recommended by your doctor",
    },
    instructions: [
      "Fast for 8-10 hours before the test",
      "Only water is allowed during fasting",
      "Take the test in the morning",
      "Avoid smoking before the test",
    ],
    parameterDetails: [
      {
        name: "Fasting Blood Glucose",
        description: "Measures the amount of glucose in blood after fasting",
        normalRange: "70-100 mg/dL",
      },
    ],
  },
  {
    id: 3,
    name: "TSH Test",
    category: "Thyroid Profile",
    categoryId: 2,
    price: 399,
    mrp: 550,
    discount: 27,
    description: "Thyroid Stimulating Hormone test to check thyroid function",
    preparationTime: "No fasting required",
    tat_time: "24 hours",
    sampleType: "Blood",
    fasting: "Not Required",
    ageGroup: "All ages",
    gender: "Both",
    parameters: 1,
    topSelling: true,
    recentBookings: 4120,
    alsoKnownAs: ["Thyroid Stimulating Hormone", "Thyrotropin"],
    testCriteria: {
      eligible: "Anyone with thyroid symptoms",
      when: "If experiencing fatigue, weight changes, or mood swings",
      frequency: "Every 6-12 months for thyroid patients",
    },
    instructions: [
      "No fasting required",
      "Can be done at any time of the day",
      "Inform about thyroid medications",
      "Avoid biotin supplements 2 days before test",
    ],
    parameterDetails: [
      {
        name: "TSH (Thyroid Stimulating Hormone)",
        description: "Measures the level of TSH in blood to assess thyroid function",
        normalRange: "0.4-4.0 mIU/L",
      },
    ],
  },
  {
    id: 4,
    name: "T3 T4 Test",
    category: "Thyroid Profile",
    categoryId: 2,
    price: 599,
    mrp: 850,
    discount: 30,
    description: "Complete thyroid hormone profile including T3 and T4 levels",
    preparationTime: "No fasting required",
    tat_time: "24 hours",
    sampleType: "Blood",
    fasting: "Not Required",
    ageGroup: "All ages",
    gender: "Both",
    parameters: 2,
    topSelling: false,
    recentBookings: 3180,
    alsoKnownAs: ["Thyroid Function Test", "TFT"],
    testCriteria: {
      eligible: "Anyone with thyroid disorders",
      when: "For comprehensive thyroid evaluation",
      frequency: "As recommended by endocrinologist",
    },
    instructions: [
      "No fasting required",
      "Morning sample preferred",
      "Inform about all medications",
      "Avoid thyroid medication on test day",
    ],
    parameterDetails: [
      {
        name: "T3 (Triiodothyronine)",
        description: "Active thyroid hormone",
        normalRange: "80-200 ng/dL",
      },
      {
        name: "T4 (Thyroxine)",
        description: "Primary thyroid hormone",
        normalRange: "5-12 μg/dL",
      },
    ],
  },
  {
    id: 5,
    name: "Liver Function Test",
    category: "Liver Function",
    categoryId: 3,
    price: 699,
    mrp: 950,
    discount: 26,
    description: "Complete liver enzyme panel to assess liver health",
    preparationTime: "8-10 hours fasting",
    tat_time: "24 hours",
    sampleType: "Blood",
    fasting: "Required",
    ageGroup: "All ages",
    gender: "Both",
    parameters: 11,
    topSelling: true,
    recentBookings: 6890,
    alsoKnownAs: ["LFT", "Hepatic Function Panel"],
    testCriteria: {
      eligible: "Anyone above 10 years",
      when: "For liver health assessment",
      frequency: "Annually or as recommended",
    },
    instructions: [
      "Fast for 8-10 hours",
      "Avoid alcohol 24 hours before test",
      "Inform about liver medications",
      "Stay hydrated",
    ],
    parameterDetails: [
      {
        name: "SGOT (AST)",
        description: "Enzyme that indicates liver damage",
        normalRange: "5-40 U/L",
      },
      {
        name: "SGPT (ALT)",
        description: "Enzyme specific to liver function",
        normalRange: "7-56 U/L",
      },
      {
        name: "Bilirubin",
        description: "Measures liver's ability to process waste",
        normalRange: "0.1-1.2 mg/dL",
      },
    ],
  },
  {
    id: 6,
    name: "Kidney Function Test (KFT)",
    category: "Kidney Function",
    categoryId: 4,
    price: 599,
    mrp: 850,
    discount: 29,
    description: "Comprehensive kidney function assessment including creatinine, urea, and electrolytes",
    preparationTime: "No fasting required",
    tat_time: "13 hours",
    sampleType: "Blood",
    fasting: "Not Required",
    ageGroup: "5+ Years",
    gender: "Both",
    parameters: 12,
    topSelling: true,
    recentBookings: 10375,
    alsoKnownAs: ["KFT", "Renal Function Test", "RFT", "Kidney Profile"],
    testCriteria: {
      eligible: "Anyone above 5 years of age can take this test",
      when: "For kidney health assessment, monitoring chronic kidney disease, or if experiencing symptoms like swelling, fatigue, or changes in urination",
      frequency: "Every 6-12 months for kidney patients, annually for general health checkup",
    },
    instructions: [
      "No fasting required for this test",
      "Drink adequate water before the test",
      "Inform your doctor about any medications you're taking",
      "Avoid strenuous exercise 24 hours before the test",
      "Continue your regular medications unless advised otherwise",
    ],
    parameterDetails: [
      {
        name: "Creatinine",
        description: "Waste product filtered by kidneys, indicates kidney function",
        normalRange: "0.7-1.3 mg/dL (men), 0.6-1.1 mg/dL (women)",
      },
      {
        name: "Blood Urea Nitrogen (BUN)",
        description: "Measures urea nitrogen in blood, indicates kidney function",
        normalRange: "7-20 mg/dL",
      },
      {
        name: "Uric Acid",
        description: "Waste product that can indicate kidney problems",
        normalRange: "3.5-7.2 mg/dL (men), 2.6-6.0 mg/dL (women)",
      },
      {
        name: "Sodium",
        description: "Electrolyte balance indicator",
        normalRange: "136-145 mEq/L",
      },
      {
        name: "Potassium",
        description: "Essential electrolyte for kidney function",
        normalRange: "3.5-5.0 mEq/L",
      },
      {
        name: "Chloride",
        description: "Electrolyte that helps maintain fluid balance",
        normalRange: "96-106 mEq/L",
      },
      {
        name: "Calcium",
        description: "Mineral regulated by kidneys",
        normalRange: "8.5-10.2 mg/dL",
      },
      {
        name: "Phosphorus",
        description: "Mineral filtered by kidneys",
        normalRange: "2.5-4.5 mg/dL",
      },
      {
        name: "Total Protein",
        description: "Measures protein levels in blood",
        normalRange: "6.0-8.3 g/dL",
      },
      {
        name: "Albumin",
        description: "Main protein in blood plasma",
        normalRange: "3.5-5.5 g/dL",
      },
      {
        name: "Globulin",
        description: "Group of proteins in blood",
        normalRange: "2.0-3.5 g/dL",
      },
      {
        name: "A/G Ratio",
        description: "Ratio of albumin to globulin",
        normalRange: "1.0-2.5",
      },
    ],
  },
]

export const packages = [
  {
    id: 1,
    name: "Complete Health Checkup",
    tests: ["CBC", "Lipid Profile", "Liver Function", "Kidney Function", "Thyroid Profile"],
    price: 1999,
    mrp: 3500,
    discount: 43,
    description: "Comprehensive health screening package covering all major body systems",
    testsCount: 65,
    tat_time: "24 hours",
    sampleType: "Blood",
    fasting: "Required",
    ageGroup: "All ages",
    gender: "Both",
    topSelling: true,
    recentBookings: 8450,
    includedTests: [
      { name: "Complete Blood Count (CBC)", parameters: 28 },
      { name: "Lipid Profile", parameters: 8 },
      { name: "Liver Function Test", parameters: 11 },
      { name: "Kidney Function Test", parameters: 12 },
      { name: "Thyroid Profile", parameters: 3 },
      { name: "Vitamin D", parameters: 1 },
      { name: "Vitamin B12", parameters: 1 },
      { name: "Iron Studies", parameters: 1 },
    ],
  },
  {
    id: 2,
    name: "Diabetes Care Package",
    tests: ["HbA1c", "Fasting Blood Sugar", "Post Prandial", "Lipid Profile"],
    price: 1299,
    mrp: 2000,
    discount: 35,
    description: "Complete diabetes monitoring package for better glucose management",
    testsCount: 25,
    tat_time: "24 hours",
    sampleType: "Blood",
    fasting: "Required",
    ageGroup: "All ages",
    gender: "Both",
    topSelling: true,
    recentBookings: 5670,
    includedTests: [
      { name: "HbA1c", parameters: 1 },
      { name: "Fasting Blood Sugar", parameters: 1 },
      { name: "Post Prandial Blood Sugar", parameters: 1 },
      { name: "Lipid Profile", parameters: 8 },
      { name: "Kidney Function Test", parameters: 12 },
      { name: "Urine Routine", parameters: 2 },
    ],
  },
  {
    id: 3,
    name: "Heart Health Package",
    tests: ["Lipid Profile", "ECG", "Cardiac Enzymes", "Blood Pressure"],
    price: 1599,
    mrp: 2500,
    discount: 36,
    description: "Comprehensive heart health screening for cardiovascular wellness",
    testsCount: 30,
    tat_time: "24 hours",
    sampleType: "Blood",
    fasting: "Required",
    ageGroup: "18+ years",
    gender: "Both",
    topSelling: false,
    recentBookings: 4230,
    includedTests: [
      { name: "Lipid Profile", parameters: 8 },
      { name: "ECG", parameters: 1 },
      { name: "Cardiac Enzymes", parameters: 5 },
      { name: "hs-CRP", parameters: 1 },
      { name: "Homocysteine", parameters: 1 },
      { name: "Complete Blood Count", parameters: 14 },
    ],
  },
  {
    id: 4,
    name: "Women Wellness Package",
    tests: ["Thyroid", "Vitamin D", "Iron Studies", "Hormone Panel"],
    price: 1799,
    mrp: 2800,
    discount: 36,
    description: "Complete wellness package designed specifically for women's health",
    testsCount: 40,
    tat_time: "48 hours",
    sampleType: "Blood",
    fasting: "Required",
    ageGroup: "18+ years",
    gender: "Female",
    topSelling: true,
    recentBookings: 6120,
    includedTests: [
      { name: "Thyroid Profile", parameters: 3 },
      { name: "Vitamin D", parameters: 1 },
      { name: "Iron Studies", parameters: 4 },
      { name: "Hormone Panel", parameters: 8 },
      { name: "Complete Blood Count", parameters: 28 },
      { name: "Calcium", parameters: 1 },
    ],
  },
  {
    id: 5,
    name: "Full Body Checkup Premium",
    tests: ["CBC", "Lipid Profile", "Liver Function", "Kidney Function", "Thyroid", "Vitamins"],
    price: 2499,
    mrp: 4500,
    discount: 44,
    description: "Most comprehensive health package with 80+ parameters",
    testsCount: 85,
    tat_time: "48 hours",
    sampleType: "Blood & Urine",
    fasting: "Required",
    ageGroup: "All ages",
    gender: "Both",
    topSelling: true,
    recentBookings: 9230,
    includedTests: [
      { name: "Complete Blood Count", parameters: 28 },
      { name: "Lipid Profile", parameters: 8 },
      { name: "Liver Function Test", parameters: 11 },
      { name: "Kidney Function Test", parameters: 12 },
      { name: "Thyroid Profile", parameters: 3 },
      { name: "Vitamin D", parameters: 1 },
      { name: "Vitamin B12", parameters: 1 },
      { name: "Iron Studies", parameters: 4 },
      { name: "Diabetes Screening", parameters: 3 },
      { name: "Urine Routine", parameters: 14 },
    ],
  },
]

export const banners = [
  {
    id: 1,
    title: "Lab Tests Made Simple",
    subtitle: "Right at Your Doorstep",
    buttonText: "Book Now",
    bgColor: "bg-gradient-to-br from-blue-600 to-blue-800",
  },
  {
    id: 2,
    title: "Get 40% OFF",
    subtitle: "On Complete Health Checkup",
    buttonText: "Claim Offer",
    bgColor: "bg-gradient-to-br from-orange-500 to-red-600",
  },
  {
    id: 3,
    title: "Free Home Sample Collection",
    subtitle: "Book Tests Worth ₹999 or More",
    buttonText: "Learn More",
    bgColor: "bg-gradient-to-br from-green-600 to-teal-700",
  },
]

export const features = [
  {
    id: 1,
    title: "Prep for Lab Test",
    icon: "📋",
    color: "bg-pink-100",
  },
  {
    id: 2,
    title: "Lab Certified",
    icon: "✓",
    color: "bg-green-100",
  },
  {
    id: 3,
    title: "Health Packages",
    icon: "📦",
    color: "bg-purple-100",
  },
]

export const testimonials = [
  {
    id: 1,
    name: "Priya Sharma",
    rating: 5,
    comment: "Very convenient service! The phlebotomist was professional and the reports came on time.",
    date: "2 days ago",
  },
  {
    id: 2,
    name: "Rajesh Kumar",
    rating: 5,
    comment: "Excellent experience. Home collection was smooth and reports were accurate.",
    date: "1 week ago",
  },
  {
    id: 3,
    name: "Anita Desai",
    rating: 4,
    comment: "Good service and affordable prices. Would recommend to others.",
    date: "2 weeks ago",
  },
]
